import { useQuery } from "convex/react";
import { Link, createFileRoute } from "@tanstack/react-router";

import { api } from "../../../convex/_generated/api.js";
import { MaterialSymbol } from "../../components/ui/MaterialSymbol";

type Variant = "technical" | "friendly";

type SearchInput = Record<string, unknown>;

function parseVariant(value: unknown): Variant {
  return value === "friendly" ? "friendly" : "technical";
}

export const Route = createFileRoute("/reports/$reportId")({
  component: ReportPage,
  validateSearch: (search: SearchInput) => ({
    variant: parseVariant(search.variant),
  }),
});

const PANEL = "border border-[#dddddd] bg-white p-6 print:p-4";

function ReportPage() {
  const { reportId } = Route.useParams();
  const { variant } = Route.useSearch();
  const detail = useQuery(api.reports.getDetail, { externalId: reportId });

  if (detail === undefined) {
    return (
      <PageShell>
        <p className="font-mono text-sm text-[#666]">Loading report…</p>
      </PageShell>
    );
  }

  if (detail === null) {
    return (
      <PageShell>
        <div className="border border-[#cccccc] bg-white p-6">
          <p className="font-mono text-sm">
            Report{" "}
            <code className="rounded bg-[#f2f2f2] px-1 py-0.5">{reportId}</code>{" "}
            was not found.
          </p>
          <Link
            to="/guardian/reports"
            className="mt-4 inline-block font-mono text-xs underline"
          >
            Back to report library
          </Link>
        </div>
      </PageShell>
    );
  }

  const { report, municipality, scan } = detail;
  const isFriendly = variant === "friendly";
  const titlePrefix = isFriendly
    ? "Plain-language remediation report"
    : "Technical remediation report";
  const audience = isFriendly
    ? "Written for non-technical readers (city leadership, staff, contractors)."
    : "Written for technical reviewers responsible for remediation.";

  return (
    <PageShell>
      <TopBar
        reportId={report.externalId}
        otherVariantHref={variantHref(report.externalId, otherVariant(variant))}
        otherVariantLabel={
          isFriendly ? "Switch to technical view" : "Switch to friendly view"
        }
      />

      <article className="report-print mx-auto mt-8 max-w-4xl space-y-6 bg-white p-8 text-[#111111] shadow-md print:mt-0 print:max-w-none print:shadow-none">
        <header className="space-y-2 border-b border-[#dddddd] pb-6">
          <p className="font-mono text-xs tracking-[0.2em] text-[#666666] uppercase">
            {titlePrefix}
          </p>
          <h1 className="font-display text-3xl font-semibold">
            Remediation report — {municipality.name}, {municipality.state}
          </h1>
          <p className="font-mono text-xs text-[#666666]">{audience}</p>
          <dl className="mt-4 grid grid-cols-1 gap-2 font-mono text-xs text-[#333333] sm:grid-cols-2">
            <DefLine label="Target" value={municipality.websiteUrl} />
            <DefLine label="Municipality ID" value={municipality.id} />
            <DefLine label="Report ID" value={report.externalId} />
            <DefLine
              label="Generated"
              value={formatDateTime(report.generatedAt)}
            />
            <DefLine label="Updated" value={formatDateTime(report.updatedAt)} />
            <DefLine
              label="Generated by"
              value={report.generatedBy ?? "unknown"}
            />
            <DefLine label="Risk tier" value={municipality.riskTier} />
            <DefLine
              label="Risk score"
              value={
                scan?.riskScore !== undefined ? String(scan.riskScore) : "—"
              }
            />
          </dl>
        </header>

        <section className={PANEL}>
          <SectionHeader
            title={isFriendly ? "Quick summary" : "Executive summary"}
          />
          <p className="font-mono text-sm leading-6 whitespace-pre-line">
            {report.summary ?? "No summary recorded."}
          </p>
        </section>

        <section className={PANEL}>
          <SectionHeader
            title={
              isFriendly
                ? "Most important next actions"
                : "Priority remediation actions"
            }
          />
          {(report.priorityActions ?? []).length === 0 ? (
            <p className="font-mono text-sm text-[#666]">
              No priority actions captured.
            </p>
          ) : (
            <ol className="ml-6 list-decimal space-y-2 font-mono text-sm leading-6">
              {(report.priorityActions ?? []).map((action) => (
                <li key={action}>{action}</li>
              ))}
            </ol>
          )}
        </section>

        <section className={PANEL}>
          <SectionHeader
            title={
              isFriendly ? "Issue-by-issue explanation" : "Detailed findings"
            }
          />
          {(report.findings ?? []).length === 0 ? (
            <p className="font-mono text-sm text-[#666]">
              No reportable findings.
            </p>
          ) : (
            <div className="space-y-4">
              {(report.findings ?? []).map((finding) => (
                <FindingCard key={finding.id} finding={finding} />
              ))}
            </div>
          )}
        </section>

        {scan ? (
          <section className={PANEL}>
            <SectionHeader title="Evidence snapshot" />
            <dl className="grid grid-cols-1 gap-2 font-mono text-xs sm:grid-cols-2">
              <DefLine
                label="Scanned at"
                value={formatDateTime(scan.scannedAt)}
              />
              <DefLine
                label="Reachable"
                value={scan.reachable === false ? "no" : "yes"}
              />
              <DefLine
                label="HTTP status"
                value={
                  scan.httpStatus !== undefined ? String(scan.httpStatus) : "—"
                }
              />
              <DefLine
                label="Final URL"
                value={scan.finalUrl ?? scan.requestedUrl ?? "—"}
              />
              <DefLine
                label="TLS valid"
                value={scan.tls ? (scan.tls.valid ? "yes" : "no") : "—"}
              />
              <DefLine label="TLS issuer" value={scan.tls?.issuer ?? "—"} />
              <DefLine label="CMS" value={scan.cms?.name ?? "—"} />
              <DefLine label="CMS version" value={scan.cms?.version ?? "—"} />
            </dl>

            {scan.adminExposure && scan.adminExposure.length > 0 ? (
              <div className="mt-4">
                <p className="font-mono text-xs tracking-[0.2em] text-[#666] uppercase">
                  Admin path checks
                </p>
                <table className="mt-2 w-full border-collapse font-mono text-xs">
                  <thead>
                    <tr className="border-b border-[#dddddd] text-left">
                      <th className="py-1">Path</th>
                      <th className="py-1">Method</th>
                      <th className="py-1">Reachable</th>
                      <th className="py-1">HTTP</th>
                    </tr>
                  </thead>
                  <tbody>
                    {scan.adminExposure.map((entry) => (
                      <tr
                        key={entry.path}
                        className="border-b border-[#eeeeee]"
                      >
                        <td className="py-1">{entry.path}</td>
                        <td className="py-1">{entry.method ?? "—"}</td>
                        <td className="py-1">
                          {entry.reachable ? "yes" : "no"}
                        </td>
                        <td className="py-1">
                          {entry.httpStatus !== undefined
                            ? String(entry.httpStatus)
                            : "—"}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : null}

            {scan.headers && Object.keys(scan.headers).length > 0 ? (
              <div className="mt-4">
                <p className="font-mono text-xs tracking-[0.2em] text-[#666] uppercase">
                  Selected response headers
                </p>
                <ul className="mt-2 space-y-1 font-mono text-xs">
                  {Object.entries(scan.headers).map(([key, value]) => (
                    <li key={key}>
                      <span className="text-[#666]">{key}:</span> {value}
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </section>
        ) : null}

        <footer className="border-t border-[#dddddd] pt-4 font-mono text-[10px] text-[#666666]">
          <p>
            Generated by OpenBreach passive review pipeline. This report
            summarizes public evidence and prioritized remediation. It does not
            assert exploitation and is bounded by the authorized scope on the
            target.
          </p>
        </footer>
      </article>
    </PageShell>
  );
}

function PageShell({ children }: { children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-[#f6f7f8] print:bg-white">
      <div className="mx-auto max-w-5xl px-4 pt-6 pb-12">{children}</div>
    </div>
  );
}

function TopBar({
  reportId,
  otherVariantHref,
  otherVariantLabel,
}: {
  reportId: string;
  otherVariantHref: string;
  otherVariantLabel: string;
}) {
  return (
    <div className="no-print flex flex-wrap items-center justify-between gap-3 border border-[#dddddd] bg-white px-4 py-3">
      <div className="flex items-center gap-2 font-mono text-xs">
        <Link
          to="/guardian/reports"
          className="text-[#333] hover:text-[#000] hover:underline"
        >
          ← Report library
        </Link>
        <span className="text-[#999]">/</span>
        <span className="text-[#666]">{reportId}</span>
      </div>
      <div className="flex flex-wrap items-center gap-3">
        <a
          className="font-mono text-xs text-[#333] hover:text-[#000] hover:underline"
          href={otherVariantHref}
        >
          {otherVariantLabel}
        </a>
        <button
          type="button"
          onClick={() => globalThis.window?.print()}
          className="inline-flex items-center gap-2 border border-[#333] bg-[#111] px-3 py-2 font-mono text-xs tracking-[0.2em] text-white uppercase hover:bg-[#000]"
        >
          <MaterialSymbol icon="print" />
          Print / Save as PDF
        </button>
      </div>
    </div>
  );
}

function SectionHeader({ title }: { title: string }) {
  return (
    <h2 className="font-display mb-3 text-lg font-semibold tracking-wide text-[#111111]">
      {title}
    </h2>
  );
}

function DefLine({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex gap-2">
      <dt className="min-w-[120px] text-[#666]">{label}</dt>
      <dd className="break-all text-[#111]">{value}</dd>
    </div>
  );
}

function FindingCard({
  finding,
}: {
  finding: NonNullable<
    NonNullable<
      ReturnType<typeof useQuery<typeof api.reports.getDetail>>
    >["report"]["findings"]
  >[number];
}) {
  const severityClass = severityToClass(finding.severity);
  return (
    <article className="border border-[#dddddd] bg-white p-4">
      <header className="flex flex-wrap items-start justify-between gap-2">
        <div>
          <p className="font-mono text-[10px] tracking-[0.2em] text-[#666] uppercase">
            {finding.category} · {finding.status} · confidence{" "}
            {finding.confidence}
          </p>
          <h3 className="font-display mt-1 text-base font-semibold">
            {finding.title}
          </h3>
        </div>
        <span
          className={`border border-current px-2 py-1 font-mono text-[10px] tracking-[0.2em] uppercase ${severityClass}`}
        >
          {finding.severity}
        </span>
      </header>
      <p className="mt-3 font-mono text-sm leading-6">{finding.description}</p>

      <DetailBlock label="Evidence" value={finding.evidence} />
      {finding.evidenceSummary &&
      finding.evidenceSummary !== finding.evidence ? (
        <DetailBlock label="Evidence summary" value={finding.evidenceSummary} />
      ) : null}

      {finding.affectedAssets?.length ? (
        <ListBlock label="Affected assets" items={finding.affectedAssets} />
      ) : null}

      {finding.remediationSteps?.length ? (
        <ListBlock label="Remediation steps" items={finding.remediationSteps} />
      ) : (
        <DetailBlock label="Remediation hint" value={finding.remediationHint} />
      )}

      {finding.verificationSteps?.length ? (
        <ListBlock
          label="Verification steps"
          items={finding.verificationSteps}
        />
      ) : null}
    </article>
  );
}

function DetailBlock({ label, value }: { label: string; value: string }) {
  return (
    <div className="mt-3">
      <p className="font-mono text-[10px] tracking-[0.2em] text-[#666] uppercase">
        {label}
      </p>
      <p className="mt-1 font-mono text-sm leading-6 whitespace-pre-line">
        {value}
      </p>
    </div>
  );
}

function ListBlock({ label, items }: { label: string; items: string[] }) {
  return (
    <div className="mt-3">
      <p className="font-mono text-[10px] tracking-[0.2em] text-[#666] uppercase">
        {label}
      </p>
      <ul className="mt-1 ml-6 list-disc space-y-1 font-mono text-sm leading-6">
        {items.map((item, index) => (
          <li key={`${label}-${index}`}>{item}</li>
        ))}
      </ul>
    </div>
  );
}

function severityToClass(severity: string): string {
  switch (severity) {
    case "critical":
      return "severity-critical text-[#8a0a0a]";
    case "high":
      return "severity-high text-[#8a0a0a]";
    case "medium":
      return "severity-medium text-[#8a5a00]";
    case "low":
      return "severity-low text-[#2f4f2f]";
    case "info":
    default:
      return "severity-info text-[#2f4f2f]";
  }
}

function formatDateTime(value: string | undefined): string {
  if (!value) {
    return "—";
  }
  try {
    return new Date(value).toLocaleString("en-US", {
      year: "numeric",
      month: "short",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
    });
  } catch {
    return value;
  }
}

function otherVariant(variant: Variant): Variant {
  return variant === "technical" ? "friendly" : "technical";
}

function variantHref(reportId: string, variant: Variant): string {
  return `/reports/${reportId}?variant=${variant}`;
}
