import {
  remediationReportSchema,
  type RemediationReport,
  type ReportAudience,
} from "../shared/contracts.ts";

function parseProviderJson(content: string): unknown {
  const trimmed = content.trim();
  const json =
    trimmed.match(/```(?:json)?\s*([\s\S]*?)\s*```/i)?.[1] ?? trimmed;
  const parsed: unknown = JSON.parse(json);

  return parsed;
}

export function parseProviderReport(
  content: string,
  expectedVariant: ReportAudience,
): RemediationReport {
  const report = remediationReportSchema.parse(parseProviderJson(content));

  if (report.variant !== expectedVariant) {
    throw new Error(
      `Provider returned ${report.variant} report for ${expectedVariant} request.`,
    );
  }

  if (report.generatedBy !== "ai-provider") {
    throw new Error(
      `Provider returned report generated by ${report.generatedBy}.`,
    );
  }

  return report;
}
