import { writeFile } from "node:fs/promises";
import { buildStyledPdfDocument } from "../src/reports/pdf-layout.ts";

const sampleMarkdown = `# Security Assessment Report

> Plain-language report for readers who do not work in technical or security roles.

## Quick summary

This report provides a comprehensive security assessment for the municipality of Springfield, identifying critical vulnerabilities that require immediate attention.

## Basic context

- Target: Springfield
- Public ID: SPR-2024-001
- Audience: Executive Leadership
- Generated at: 2024-01-15T10:30:00Z
- Generated by: OPEN CREACH Security Team

## Most important next actions

- Immediately patch critical CVE-2024-1234 on all production servers
- Implement multi-factor authentication for all admin accounts
- Review and restrict network access to sensitive endpoints

## What this report covers

The assessment covered external-facing infrastructure including:

- Web application firewalls
- API endpoints
- Authentication systems
- Data storage systems

## What was allowed

Access was granted to:

- Read-only database replicas
- Log aggregation systems
- Monitoring dashboards

## How the review was done

Our methodology included:

- Automated vulnerability scanning
- Manual penetration testing
- Code review of custom applications
- Network traffic analysis

## What needs attention

Multiple high-severity issues were identified:

- SQL injection vulnerability in the citizen portal
- Outdated OpenSSL libraries
- Missing rate limiting on public APIs

## Issue-by-issue explanation

### Critical: SQL Injection in Citizen Portal

The citizen portal at https://citizen.springfield.gov contains a SQL injection vulnerability in the search parameter. An attacker could extract sensitive citizen data including names, addresses, and tax records.

### High: Outdated OpenSSL

Server prod-web-03 is running OpenSSL 1.0.2 which is no longer supported. This version contains known vulnerabilities that could allow remote code execution.

### Medium: Missing Rate Limiting

The public API endpoint /api/v2/residents does not implement rate limiting, making it vulnerable to brute force attacks.

## What was not tested

The following areas were explicitly excluded:

- Internal network segmentation
- Physical security controls
- Vendor management systems

## What the current evidence confirms

Our validation confirmed:

- Encryption at rest is properly implemented
- TLS 1.3 is enforced on all public endpoints
- Access logs are retained for 90 days

## Important limits

This assessment has the following limitations:

- No internal network access was provided
- Testing was performed from external perspective only
- Limited scope to production systems only

## Recommended next actions

- Deploy Web Application Firewall rules to block SQL injection attempts
- Schedule emergency maintenance window to update OpenSSL
- Implement API rate limiting using nginx

## How to check the fixes

To verify each fix:

1. SQL Injection: Run the provided test suite against the staging environment
2. OpenSSL: Verify version with \`openssl version\` command
3. Rate Limiting: Use the included load testing script to confirm limits are enforced`;

const technicalMarkdown = `# Technical Remediation Report

> Formal technical remediation report generated from normalized structured evidence.

## Executive summary

Critical security vulnerabilities require immediate remediation to prevent potential data breaches and service disruption.

## Report context

- Target: Springfield Municipality
- Public ID: SPR-2024-001
- Audience: Technical Security Team
- Generated at: 2024-01-15T10:30:00Z
- Generated by: OPEN CREACH

## Priority actions

- Patch CVE-2024-1234 within 24 hours
- Update OpenSSL to version 3.0 or higher
- Implement rate limiting on public API endpoints

## Scope

External attack surface assessment covering:

- Public web applications
- API infrastructure
- Authentication systems
- Data storage endpoints

## Findings overview

- 1 Critical severity finding
- 2 High severity findings
- 3 Medium severity findings
- 5 Low severity findings

## Detailed findings

### CRITICAL-001: SQL Injection in Citizen Portal

**Severity:** Critical
**CVSS Score:** 9.8
**Affected Component:** citizen.springfield.gov/search
**Description:** Unsanitized user input in SQL query allows data exfiltration
**Remediation:** Use parameterized queries, implement input validation
**Timeline:** Immediately

### HIGH-001: Outdated OpenSSL Version

**Severity:** High
**CVSS Score:** 7.5
**Affected Component:** prod-web-03.internal
**Description:** Running unsupported OpenSSL 1.0.2 with known vulnerabilities
**Remediation:** Upgrade to OpenSSL 3.0+
**Timeline:** Within 72 hours

### HIGH-002: Missing Rate Limiting

**Severity:** High
**CVSS Score:** 6.1
**Affected Component:** /api/v2/residents
**Description:** No rate limiting enables brute force attacks
**Remediation:** Implement nginx rate limiting rules
**Timeline:** Within 1 week

## Remediation checklist

- [ ] Apply SQL injection fix to production
- [ ] Update OpenSSL on prod-web-03
- [ ] Configure rate limiting rules
- [ ] Run vulnerability scan to confirm fixes
- [ ] Update documentation

## Verification guidance

All fixes must be verified through:

1. Automated security testing
2. Manual code review
3. Staged deployment to production`;

async function main() {
  console.log("Generating friendly report PDF...");
  const friendlyPdf = await buildStyledPdfDocument(sampleMarkdown, "friendly");
  await writeFile("/Users/jerifcornejo/Downloads/friendly-report-preview.pdf", friendlyPdf);
  console.log("Saved to /Users/jerifcornejo/Downloads/friendly-report-preview.pdf");

  console.log("Generating technical report PDF...");
  const technicalPdf = await buildStyledPdfDocument(technicalMarkdown, "technical");
  await writeFile("/Users/jerifcornejo/Downloads/technical-report-preview.pdf", technicalPdf);
  console.log("Saved to /Users/jerifcornejo/Downloads/technical-report-preview.pdf");
}

main().catch(console.error);