/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TargetsIndexRouteImport } from './routes/targets/index'
import { Route as TargetsNewRouteImport } from './routes/targets/new'
import { Route as ReportsFileNameRouteImport } from './routes/reports/$fileName'
import { Route as MunicipalitiesIdRouteImport } from './routes/municipalities.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsIndexRoute = TargetsIndexRouteImport.update({
  id: '/targets/',
  path: '/targets/',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsNewRoute = TargetsNewRouteImport.update({
  id: '/targets/new',
  path: '/targets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsFileNameRoute = ReportsFileNameRouteImport.update({
  id: '/reports/$fileName',
  path: '/reports/$fileName',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipalitiesIdRoute = MunicipalitiesIdRouteImport.update({
  id: '/municipalities/$id',
  path: '/municipalities/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/municipalities/$id': typeof MunicipalitiesIdRoute
  '/reports/$fileName': typeof ReportsFileNameRoute
  '/targets/new': typeof TargetsNewRoute
  '/targets/': typeof TargetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/municipalities/$id': typeof MunicipalitiesIdRoute
  '/reports/$fileName': typeof ReportsFileNameRoute
  '/targets/new': typeof TargetsNewRoute
  '/targets': typeof TargetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/municipalities/$id': typeof MunicipalitiesIdRoute
  '/reports/$fileName': typeof ReportsFileNameRoute
  '/targets/new': typeof TargetsNewRoute
  '/targets/': typeof TargetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/municipalities/$id'
    | '/reports/$fileName'
    | '/targets/new'
    | '/targets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/municipalities/$id'
    | '/reports/$fileName'
    | '/targets/new'
    | '/targets'
  id:
    | '__root__'
    | '/'
    | '/municipalities/$id'
    | '/reports/$fileName'
    | '/targets/new'
    | '/targets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MunicipalitiesIdRoute: typeof MunicipalitiesIdRoute
  ReportsFileNameRoute: typeof ReportsFileNameRoute
  TargetsNewRoute: typeof TargetsNewRoute
  TargetsIndexRoute: typeof TargetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets/': {
      id: '/targets/'
      path: '/targets'
      fullPath: '/targets/'
      preLoaderRoute: typeof TargetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets/new': {
      id: '/targets/new'
      path: '/targets/new'
      fullPath: '/targets/new'
      preLoaderRoute: typeof TargetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$fileName': {
      id: '/reports/$fileName'
      path: '/reports/$fileName'
      fullPath: '/reports/$fileName'
      preLoaderRoute: typeof ReportsFileNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipalities/$id': {
      id: '/municipalities/$id'
      path: '/municipalities/$id'
      fullPath: '/municipalities/$id'
      preLoaderRoute: typeof MunicipalitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MunicipalitiesIdRoute: MunicipalitiesIdRoute,
  ReportsFileNameRoute: ReportsFileNameRoute,
  TargetsNewRoute: TargetsNewRoute,
  TargetsIndexRoute: TargetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
