/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TargetsIndexRouteImport } from './routes/targets/index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as GuardianIndexRouteImport } from './routes/guardian/index'
import { Route as TargetsNewRouteImport } from './routes/targets/new'
import { Route as TargetsTargetIdRouteImport } from './routes/targets/$targetId'
import { Route as SignUpSplatRouteImport } from './routes/sign-up/$'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as ReportsReportIdRouteImport } from './routes/reports/$reportId'
import { Route as GuardianValidationsRouteImport } from './routes/guardian/validations'
import { Route as GuardianThreatsRouteImport } from './routes/guardian/threats'
import { Route as GuardianRunsRouteImport } from './routes/guardian/runs'
import { Route as GuardianReportsRouteImport } from './routes/guardian/reports'
import { Route as GuardianNetworkRouteImport } from './routes/guardian/network'
import { Route as GuardianLogsRouteImport } from './routes/guardian/logs'
import { Route as GuardianEvidenceRouteImport } from './routes/guardian/evidence'
import { Route as GuardianConfigRouteImport } from './routes/guardian/config'

const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsIndexRoute = TargetsIndexRouteImport.update({
  id: '/targets/',
  path: '/targets/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianIndexRoute = GuardianIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuardianRoute,
} as any)
const TargetsNewRoute = TargetsNewRouteImport.update({
  id: '/targets/new',
  path: '/targets/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetsTargetIdRoute = TargetsTargetIdRouteImport.update({
  id: '/targets/$targetId',
  path: '/targets/$targetId',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianValidationsRoute = GuardianValidationsRouteImport.update({
  id: '/validations',
  path: '/validations',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianThreatsRoute = GuardianThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianRunsRoute = GuardianRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianReportsRoute = GuardianReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianNetworkRoute = GuardianNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianLogsRoute = GuardianLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianEvidenceRoute = GuardianEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => GuardianRoute,
} as any)
const GuardianConfigRoute = GuardianConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => GuardianRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guardian': typeof GuardianRouteWithChildren
  '/guardian/config': typeof GuardianConfigRoute
  '/guardian/evidence': typeof GuardianEvidenceRoute
  '/guardian/logs': typeof GuardianLogsRoute
  '/guardian/network': typeof GuardianNetworkRoute
  '/guardian/reports': typeof GuardianReportsRoute
  '/guardian/runs': typeof GuardianRunsRoute
  '/guardian/threats': typeof GuardianThreatsRoute
  '/guardian/validations': typeof GuardianValidationsRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/targets/$targetId': typeof TargetsTargetIdRoute
  '/targets/new': typeof TargetsNewRoute
  '/guardian/': typeof GuardianIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/targets/': typeof TargetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guardian/config': typeof GuardianConfigRoute
  '/guardian/evidence': typeof GuardianEvidenceRoute
  '/guardian/logs': typeof GuardianLogsRoute
  '/guardian/network': typeof GuardianNetworkRoute
  '/guardian/reports': typeof GuardianReportsRoute
  '/guardian/runs': typeof GuardianRunsRoute
  '/guardian/threats': typeof GuardianThreatsRoute
  '/guardian/validations': typeof GuardianValidationsRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/targets/$targetId': typeof TargetsTargetIdRoute
  '/targets/new': typeof TargetsNewRoute
  '/guardian': typeof GuardianIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/targets': typeof TargetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guardian': typeof GuardianRouteWithChildren
  '/guardian/config': typeof GuardianConfigRoute
  '/guardian/evidence': typeof GuardianEvidenceRoute
  '/guardian/logs': typeof GuardianLogsRoute
  '/guardian/network': typeof GuardianNetworkRoute
  '/guardian/reports': typeof GuardianReportsRoute
  '/guardian/runs': typeof GuardianRunsRoute
  '/guardian/threats': typeof GuardianThreatsRoute
  '/guardian/validations': typeof GuardianValidationsRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/targets/$targetId': typeof TargetsTargetIdRoute
  '/targets/new': typeof TargetsNewRoute
  '/guardian/': typeof GuardianIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/targets/': typeof TargetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guardian'
    | '/guardian/config'
    | '/guardian/evidence'
    | '/guardian/logs'
    | '/guardian/network'
    | '/guardian/reports'
    | '/guardian/runs'
    | '/guardian/threats'
    | '/guardian/validations'
    | '/reports/$reportId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/targets/$targetId'
    | '/targets/new'
    | '/guardian/'
    | '/sign-in/'
    | '/sign-up/'
    | '/targets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guardian/config'
    | '/guardian/evidence'
    | '/guardian/logs'
    | '/guardian/network'
    | '/guardian/reports'
    | '/guardian/runs'
    | '/guardian/threats'
    | '/guardian/validations'
    | '/reports/$reportId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/targets/$targetId'
    | '/targets/new'
    | '/guardian'
    | '/sign-in'
    | '/sign-up'
    | '/targets'
  id:
    | '__root__'
    | '/'
    | '/guardian'
    | '/guardian/config'
    | '/guardian/evidence'
    | '/guardian/logs'
    | '/guardian/network'
    | '/guardian/reports'
    | '/guardian/runs'
    | '/guardian/threats'
    | '/guardian/validations'
    | '/reports/$reportId'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/targets/$targetId'
    | '/targets/new'
    | '/guardian/'
    | '/sign-in/'
    | '/sign-up/'
    | '/targets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuardianRoute: typeof GuardianRouteWithChildren
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  TargetsTargetIdRoute: typeof TargetsTargetIdRoute
  TargetsNewRoute: typeof TargetsNewRoute
  SignInIndexRoute: typeof SignInIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  TargetsIndexRoute: typeof TargetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets/': {
      id: '/targets/'
      path: '/targets'
      fullPath: '/targets/'
      preLoaderRoute: typeof TargetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/': {
      id: '/guardian/'
      path: '/'
      fullPath: '/guardian/'
      preLoaderRoute: typeof GuardianIndexRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/targets/new': {
      id: '/targets/new'
      path: '/targets/new'
      fullPath: '/targets/new'
      preLoaderRoute: typeof TargetsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/targets/$targetId': {
      id: '/targets/$targetId'
      path: '/targets/$targetId'
      fullPath: '/targets/$targetId'
      preLoaderRoute: typeof TargetsTargetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/validations': {
      id: '/guardian/validations'
      path: '/validations'
      fullPath: '/guardian/validations'
      preLoaderRoute: typeof GuardianValidationsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/threats': {
      id: '/guardian/threats'
      path: '/threats'
      fullPath: '/guardian/threats'
      preLoaderRoute: typeof GuardianThreatsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/runs': {
      id: '/guardian/runs'
      path: '/runs'
      fullPath: '/guardian/runs'
      preLoaderRoute: typeof GuardianRunsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/reports': {
      id: '/guardian/reports'
      path: '/reports'
      fullPath: '/guardian/reports'
      preLoaderRoute: typeof GuardianReportsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/network': {
      id: '/guardian/network'
      path: '/network'
      fullPath: '/guardian/network'
      preLoaderRoute: typeof GuardianNetworkRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/logs': {
      id: '/guardian/logs'
      path: '/logs'
      fullPath: '/guardian/logs'
      preLoaderRoute: typeof GuardianLogsRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/evidence': {
      id: '/guardian/evidence'
      path: '/evidence'
      fullPath: '/guardian/evidence'
      preLoaderRoute: typeof GuardianEvidenceRouteImport
      parentRoute: typeof GuardianRoute
    }
    '/guardian/config': {
      id: '/guardian/config'
      path: '/config'
      fullPath: '/guardian/config'
      preLoaderRoute: typeof GuardianConfigRouteImport
      parentRoute: typeof GuardianRoute
    }
  }
}

interface GuardianRouteChildren {
  GuardianConfigRoute: typeof GuardianConfigRoute
  GuardianEvidenceRoute: typeof GuardianEvidenceRoute
  GuardianLogsRoute: typeof GuardianLogsRoute
  GuardianNetworkRoute: typeof GuardianNetworkRoute
  GuardianReportsRoute: typeof GuardianReportsRoute
  GuardianRunsRoute: typeof GuardianRunsRoute
  GuardianThreatsRoute: typeof GuardianThreatsRoute
  GuardianValidationsRoute: typeof GuardianValidationsRoute
  GuardianIndexRoute: typeof GuardianIndexRoute
}

const GuardianRouteChildren: GuardianRouteChildren = {
  GuardianConfigRoute: GuardianConfigRoute,
  GuardianEvidenceRoute: GuardianEvidenceRoute,
  GuardianLogsRoute: GuardianLogsRoute,
  GuardianNetworkRoute: GuardianNetworkRoute,
  GuardianReportsRoute: GuardianReportsRoute,
  GuardianRunsRoute: GuardianRunsRoute,
  GuardianThreatsRoute: GuardianThreatsRoute,
  GuardianValidationsRoute: GuardianValidationsRoute,
  GuardianIndexRoute: GuardianIndexRoute,
}

const GuardianRouteWithChildren = GuardianRoute._addFileChildren(
  GuardianRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuardianRoute: GuardianRouteWithChildren,
  ReportsReportIdRoute: ReportsReportIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  TargetsTargetIdRoute: TargetsTargetIdRoute,
  TargetsNewRoute: TargetsNewRoute,
  SignInIndexRoute: SignInIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  TargetsIndexRoute: TargetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
